// Approved-source and generator tests.
//
// `lib/office-map.json` is generated by `scripts/build-approved-office-map.ts`
// from four approved, read-only review artifacts. These tests pin:
//   - the coordinate transform anchors and extents,
//   - the selected artifact hashes (and that the selection doc matches disk),
//   - drift rejection when a source byte changes,
//   - deterministic output that is byte-identical to the shipped manifest,
//   - the generator's own approved assertions.

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { copyFileSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { validateManifest } from '../lib/office-map.ts';
import { buildApprovedManifest, loadApprovedSources, round2, validateApprovedManifest, worldX, worldY } from '../scripts/build-approved-office-map.ts';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, '..');
const REVIEW_DIR = resolve(ROOT, 'docs', 'reviews');

const sha256 = (path: string): string => createHash('sha256').update(readFileSync(path)).digest('hex');

// ---------------------------------------------------------------------------
// Transform
// ---------------------------------------------------------------------------

void test('the coordinate transform maps the approved source extents into the world', () => {
  // Corners of the source plan (x44..1465, y41..761) map inside 1920x960.
  assert.equal(worldX(44), 60);
  assert.equal(worldY(41), 40);
  assert.equal(worldX(1465), 1836.25);
  assert.equal(worldY(761), 940);
  // A spot used by the tests.
  assert.equal(worldX(537), 676.25);
  assert.equal(worldY(501), 615);
  // Uniform 1.25 scale on both axes.
  assert.equal(round2(worldX(144) - worldX(44)), 125);
  assert.equal(round2(worldY(141) - worldY(41)), 125);
  // Rounding is half-up to 2 decimals.
  assert.equal(round2(1004.6125), 1004.61);
  assert.equal(round2(333.75), 333.75);
});

// ---------------------------------------------------------------------------
// Approved selection + hashes
// ---------------------------------------------------------------------------

void test('the selection doc lists the four selected artifacts with their current SHA256', () => {
  const doc = JSON.parse(readFileSync(resolve(REVIEW_DIR, 'approved-map-selection.json'), 'utf8')) as {
    selected: Array<{ file: string; sha256: string }>;
    superseded: Array<{ file: string; sha256: string }>;
  };
  assert.equal(doc.selected.length, 4, 'four selected sources');
  for (const entry of [...doc.selected, ...doc.superseded]) {
    const path = resolve(ROOT, entry.file);
    assert.equal(sha256(path), entry.sha256, `sha256 for ${entry.file}`);
  }
});

void test('loadApprovedSources accepts the current approved bytes', () => {
  const sources = loadApprovedSources();
  assert.equal(sources.structure.rooms.length, 18);
  assert.equal(sources.structure.columns.length, 3);
  assert.equal(sources.structure.lifts.length, 4);
  assert.ok(sources.workareas.overrides.structure.some((override) => override.id === 'OV-TOP-OPEN'));
  assert.equal(sources.workareas.board.rect.x2 - sources.workareas.board.rect.x1, 7);
});

void test('loadApprovedSources rejects a drifted source byte', () => {
  const dir = mkdtempSync(join(tmpdir(), 'approved-sources-'));
  try {
    for (const file of [
      'office-structure-review-v2.json',
      'office-furniture-review-v1.json',
      'office-pantry-service-focus-v1.json',
      'office-workareas-focus-v4.json',
    ]) {
      copyFileSync(resolve(REVIEW_DIR, file), resolve(dir, file));
    }
    // Tamper one byte of the structure source.
    const target = resolve(dir, 'office-structure-review-v2.json');
    writeFileSync(target, `${readFileSync(target, 'utf8')} `);
    assert.throws(() => loadApprovedSources(dir), /sha256 drift/i);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

// ---------------------------------------------------------------------------
// Deterministic generation
// ---------------------------------------------------------------------------

void test('the generator output is deterministic and matches the shipped manifest', () => {
  const sources = loadApprovedSources();
  const first = JSON.stringify(buildApprovedManifest(sources), null, 2);
  const second = JSON.stringify(buildApprovedManifest(sources), null, 2);
  assert.equal(first, second, 'two builds are byte-identical');

  const shipped = readFileSync(resolve(ROOT, 'lib', 'office-map.json'), 'utf8');
  assert.equal(`${first}\n`, shipped, 'lib/office-map.json is the generated output');
});

void test('the generated manifest passes both the strict and the approved validation', () => {
  const sources = loadApprovedSources();
  const manifest = buildApprovedManifest(sources);
  assert.doesNotThrow(() => validateManifest(manifest));
  assert.doesNotThrow(() => validateApprovedManifest(manifest, sources));
});

void test('approved validation rejects a manifest with an extra forbidden zone name', () => {
  const sources = loadApprovedSources();
  const manifest = buildApprovedManifest(sources);
  const broken = structuredClone(manifest);
  broken.zones.push({ id: 'koridor-bawah', name: 'Koridor Bawah', kind: 'corridor', rect: { x: 100, y: 100, w: 50, h: 50 } });
  assert.throws(() => validateApprovedManifest(broken, sources), /forbidden/i);
});
