// Geometry + manifest tests for the final 1920x960 vector office world.
//
// The shipped `lib/office-map.json` is now GENERATED by
// `scripts/build-approved-office-map.ts` from the approved review artifacts
// (see docs/reviews/approved-map-selection.json). These tests pin the final
// approved topology, the exact furnished inventory, the derived semantics
// (open Tele top, open Wastafel path, sealed toilets/Gudang/Server, wall-mounted
// Best Agent board) and a grid BFS with the real 18x12 actor footprint.
//
// The pure geometry primitives, collision model, lookups, hotspot proximity and
// camera clamping keep the same contract as before.

import { test } from 'node:test';
import assert from 'node:assert/strict';

import {
  BILIK_GENG_ZONE_ID,
  DEFAULT_HOTSPOT_RANGE,
  MapValidationError,
  actorFootBox,
  clampCamera,
  intersectRect,
  isBlocked,
  isWalkable,
  nearestHotspot,
  officeMap,
  rectArea,
  rectContainsPoint,
  rectContainsRect,
  seatFor,
  validateManifest,
  zoneAt,
  type FurnitureKind,
  type HotspotKind,
  type OfficeManifest,
  type Point,
  type Rect,
} from '../lib/office-map.ts';

const clone = (): OfficeManifest => structuredClone(officeMap);

// Transform anchors from the approved source pixels (see the generator).
const worldX = (x: number): number => Math.round((60 + (x - 44) * 1.25) * 100) / 100;
const worldY = (y: number): number => Math.round((40 + (y - 41) * 1.25) * 100) / 100;

// ---------------------------------------------------------------------------
// Manifest shape + validation
// ---------------------------------------------------------------------------

void test('manifest declares a 1920x960 world with six seats inside Bilik Geng Kami', () => {
  assert.equal(officeMap.width, 1920);
  assert.equal(officeMap.height, 960);
  assert.ok(officeMap.margin > 0 && officeMap.margin < 100);
  assert.ok(officeMap.actor.halfWidth > 0 && officeMap.actor.feet > 0);
  assert.equal(officeMap.seats.length, 6);

  const geng = officeMap.zones.find((zone) => zone.id === BILIK_GENG_ZONE_ID);
  assert.ok(geng, 'a Bilik Geng Kami zone exists');
  assert.equal(geng?.name, 'Bilik Geng Kami');

  for (const seat of officeMap.seats) {
    assert.equal(seat.zone, BILIK_GENG_ZONE_ID, `${seat.id} is assigned to Bilik Geng Kami`);
    assert.ok(rectContainsPoint(geng!.rect, seat.x, seat.y), `${seat.id} sits inside the room rect`);
  }
  assert.deepEqual(
    officeMap.seats.map((seat) => seat.cid),
    [1, 2, 3, 4, 5, 6],
  );
});

void test('the shipped manifest passes strict validation', () => {
  assert.doesNotThrow(() => validateManifest(officeMap));
});

void test('all geometry ids are unique across every collection', () => {
  const ids: string[] = [];
  for (const group of [
    officeMap.seats,
    officeMap.zones,
    officeMap.walls,
    officeMap.columns,
    officeMap.blocks,
    officeMap.furniture,
    officeMap.openings,
    officeMap.windows,
    officeMap.hotspots,
  ]) {
    for (const entry of group) ids.push(entry.id);
  }
  assert.equal(new Set(ids).size, ids.length, 'duplicate geometry id');
});

void test('every zone, collider and hotspot lies inside the world', () => {
  const inside = (rect: Rect): boolean => rect.x >= 0 && rect.y >= 0 && rect.x + rect.w <= officeMap.width && rect.y + rect.h <= officeMap.height;
  for (const group of [officeMap.zones, officeMap.walls, officeMap.columns, officeMap.blocks, officeMap.furniture, officeMap.hotspots, officeMap.openings, officeMap.windows]) {
    for (const entry of group) assert.ok(inside(entry.rect), `${entry.id} is inside the world`);
  }
});

void test('every furniture, seat, hotspot and surface references a real zone', () => {
  const zoneIds = new Set(officeMap.zones.map((zone) => zone.id));
  for (const item of officeMap.furniture) assert.ok(zoneIds.has(item.zone), `furniture ${item.id} references ${item.zone}`);
  for (const seat of officeMap.seats) assert.ok(zoneIds.has(seat.zone), `seat ${seat.id} references ${seat.zone}`);
  for (const hotspot of officeMap.hotspots) assert.ok(zoneIds.has(hotspot.zone), `hotspot ${hotspot.id} references ${hotspot.zone}`);
  for (const surface of officeMap.surfaces) assert.ok(zoneIds.has(surface.zone), `surface references ${surface.zone}`);
});

void test('seat cids are unique', () => {
  const cids = officeMap.seats.map((seat) => seat.cid);
  assert.equal(new Set(cids).size, cids.length);
});

void test('validation rejects a duplicate id with a clear error', () => {
  const bad = clone();
  bad.zones.push({ ...bad.zones[0]! });
  assert.throws(() => validateManifest(bad), (error: unknown) => error instanceof MapValidationError && /duplicate/i.test(error.message));
});

void test('validation rejects geometry outside the world', () => {
  const bad = clone();
  bad.zones.push({ id: 'over-the-edge', name: 'Over', kind: 'open', rect: { x: 1900, y: 100, w: 200, h: 200 } });
  assert.throws(() => validateManifest(bad), (error: unknown) => error instanceof MapValidationError && /world|bounds/i.test(error.message));
});

void test('validation rejects a non-positive rectangle', () => {
  const bad = clone();
  bad.walls.push({ id: 'flat-wall', kind: 'full', rect: { x: 100, y: 100, w: 0, h: 40 } });
  assert.throws(() => validateManifest(bad), MapValidationError);
});

void test('validation rejects a seat that is not inside Bilik Geng Kami', () => {
  const bad = clone();
  bad.seats[0]!.x = 600;
  bad.seats[0]!.y = 600;
  assert.throws(() => validateManifest(bad), (error: unknown) => error instanceof MapValidationError && /Bilik Geng Kami/.test(error.message));
});

void test('validation rejects a seat that is not walkable', () => {
  const bad = clone();
  const desk = bad.furniture.find((entry) => entry.solid && entry.zone === BILIK_GENG_ZONE_ID)!;
  bad.seats[0]!.x = desk.rect.x + desk.rect.w / 2;
  bad.seats[0]!.y = desk.rect.y + desk.rect.h / 2;
  assert.throws(() => validateManifest(bad), (error: unknown) => error instanceof MapValidationError && /walkable/i.test(error.message));
});

void test('validation rejects an unknown zone reference and a bad actor', () => {
  const badSurface = clone();
  badSurface.surfaces.push({ zone: 'nowhere', kind: 'office' });
  assert.throws(() => validateManifest(badSurface), (error: unknown) => error instanceof MapValidationError && /zone/i.test(error.message));

  const badActor = clone();
  badActor.actor.halfWidth = 0;
  assert.throws(() => validateManifest(badActor), MapValidationError);
});

// ---------------------------------------------------------------------------
// Final approved structure
// ---------------------------------------------------------------------------

void test('there is no forbidden Koridor Servis / Koridor Bawah zone, label or collider', () => {
  const offenders = [
    ...officeMap.zones.map((zone) => `${zone.id} ${zone.name}`),
    ...officeMap.blocks.map((block) => `${block.id} ${block.name}`),
    ...officeMap.openings.map((opening) => opening.id),
    ...officeMap.furniture.map((item) => item.id),
  ].filter((text) => /koridor\s+(servis|bawah)/i.test(text));
  assert.deepEqual(offenders, []);
});

void test('the main circulation is lorong-utama and the open strip is jalur-terbuka', () => {
  const lorong = officeMap.zones.find((zone) => zone.id === 'lorong-utama');
  assert.ok(lorong, 'lorong-utama exists');
  assert.equal(lorong?.kind, 'corridor');

  const jalur = officeMap.zones.find((zone) => zone.id === 'jalur-terbuka');
  assert.ok(jalur, 'jalur-terbuka exists');
  assert.equal(jalur?.kind, 'corridor');
  assert.ok(jalur!.rect.y <= worldY(244) + 0.01, 'the strip starts at the main circulation');
  assert.ok(jalur!.rect.y + jalur!.rect.h <= worldY(476) + 0.01, 'the strip stops at the Wastafel wall');
});

void test('unlabelled transit/tiny zones keep their name for zoneAt but are not painted', () => {
  for (const id of ['sirkulasi', 'jalur-terbuka', 'wastafel']) {
    const zone = officeMap.zones.find((entry) => entry.id === id);
    assert.ok(zone, `${id} exists for semantics`);
    assert.ok(zone!.name.length > 0, `${id} keeps its name`);
    assert.equal(zone!.showLabel, false, `${id} is not painted`);
    const cx = zone!.rect.x + zone!.rect.w / 2;
    const cy = zone!.rect.y + zone!.rect.h / 2;
    assert.equal(zoneAt(officeMap, cx, cy)?.id, id, `${id} still resolves through zoneAt`);
  }
  for (const id of ['meeting-1', 'hrga', 'komisaris', 'product-manager', 'it', 'direktur-finance', 'bilik-geng-kami', 'resepsionis', 'lobby-besar', 'pantry', 'gudang', 'toilet-wanita', 'toilet-pria', 'meeting-2', 'server', 'desk-collection', 'tele-cs-ca', 'lorong-utama']) {
    const zone = officeMap.zones.find((entry) => entry.id === id)!;
    assert.notEqual(zone.showLabel, false, `${id} keeps its room label`);
  }
});

void test('there are exactly three structural columns', () => {
  assert.equal(officeMap.columns.length, 3);
  assert.deepEqual(officeMap.columns.map((column) => column.id).sort(), ['col-geng-1', 'col-komisaris', 'col-meeting-1']);
});

void test('Desk Collection and Tele stop at the service block and do not extend downward', () => {
  for (const id of ['desk-collection', 'tele-cs-ca']) {
    const zone = officeMap.zones.find((entry) => entry.id === id)!;
    assert.equal(zone.rect.y + zone.rect.h, worldY(501), `${id} ends at source y=501`);
  }
  const below = [...officeMap.walls, ...officeMap.furniture].filter((entry) => entry.rect.y > worldY(501) + 2 && entry.rect.x + entry.rect.w > worldX(695));
  assert.deepEqual(below.map((entry) => entry.id), []);
});

void test('the six assigned seats map to the six approved Bilik Geng Kami chairs', () => {
  for (let i = 1; i <= 6; i += 1) {
    const chair = officeMap.furniture.find((item) => item.id === `F-GENG-C${i}`);
    const seat = officeMap.seats.find((entry) => entry.cid === i)!;
    assert.ok(chair, `approved chair F-GENG-C${i} exists`);
    assert.equal(seat.x, Math.round((chair!.rect.x + chair!.rect.w / 2) * 100) / 100);
    assert.equal(seat.y, Math.round((chair!.rect.y + chair!.rect.h / 2) * 100) / 100);
  }
  assert.deepEqual(
    officeMap.seats.map((seat) => `${seat.cid}:${seat.direction}`),
    ['1:down', '2:down', '3:up', '4:up', '5:right', '6:left'],
  );
});

// ---------------------------------------------------------------------------
// Approved furniture inventory
// ---------------------------------------------------------------------------

const EXPECTED_INVENTORY: Record<string, Partial<Record<FurnitureKind, number>>> = {
  'meeting-1': { table: 1, chair: 6 },
  hrga: { desk: 2, chair: 4, cabinet: 1, dispenser: 1 },
  komisaris: { desk: 1, chair: 1 },
  'product-manager': { desk: 1, chair: 1 },
  it: { desk: 2, chair: 2 },
  'direktur-finance': { desk: 2, counter: 1, chair: 2 },
  'bilik-geng-kami': { desk: 2, chair: 6, cabinet: 1 },
  resepsionis: { counter: 1, chair: 1, sofa: 4 },
  'lorong-utama': { dispenser: 2 },
  pantry: { counter: 1, dispenser: 1, fridge: 1, chair: 1 },
  'meeting-2': { table: 2, chair: 6 },
  sirkulasi: { table: 2, chair: 2 },
  'desk-collection': { desk: 2, chair: 34, board: 1 },
  'tele-cs-ca': { desk: 2, chair: 24 },
};

void test('furniture matches the exact approved count per room', () => {
  const actual = new Map<string, Map<FurnitureKind, number>>();
  for (const item of officeMap.furniture) {
    const inner = actual.get(item.zone) ?? new Map<FurnitureKind, number>();
    inner.set(item.kind, (inner.get(item.kind) ?? 0) + 1);
    actual.set(item.zone, inner);
  }
  const sortEntries = (entries: Array<[string, number]>): Array<[string, number]> => [...entries].sort((a, b) => (a[0] < b[0] ? -1 : a[0] > b[0] ? 1 : 0));
  for (const [zone, expected] of Object.entries(EXPECTED_INVENTORY)) {
    const got = actual.get(zone) ?? new Map<FurnitureKind, number>();
    assert.deepEqual(Object.fromEntries(sortEntries([...got.entries()])), Object.fromEntries(sortEntries(Object.entries(expected))), `inventory for ${zone}`);
  }
  for (const zone of ['gudang', 'toilet-wanita', 'toilet-pria', 'wastafel', 'server']) {
    assert.equal(officeMap.furniture.filter((item) => item.zone === zone).length, 0, `no invented furniture in ${zone}`);
  }
});

void test('Desk Collection and Tele carry the approved banks and visible chairs', () => {
  assert.equal(officeMap.furniture.filter((item) => item.zone === 'desk-collection' && item.kind === 'chair').length, 34);
  assert.equal(officeMap.furniture.filter((item) => item.zone === 'tele-cs-ca' && item.kind === 'chair').length, 24);
  assert.equal(officeMap.furniture.filter((item) => item.id === 'F-DC-BANK-TOP' || item.id === 'F-DC-BANK-BOTTOM').length, 2);
  assert.equal(officeMap.furniture.filter((item) => item.id === 'F-TC-BANK-L' || item.id === 'F-TC-BANK-R').length, 2);
});

void test('chairs/sofas/board are decorative and hard furniture is solid', () => {
  for (const item of officeMap.furniture) {
    if (item.kind === 'chair' || item.kind === 'sofa' || item.kind === 'board') {
      assert.equal(item.solid, false, `${item.id} (${item.kind}) must be non-solid`);
    } else {
      assert.equal(item.solid, true, `${item.id} (${item.kind}) must be solid`);
    }
  }
});

// ---------------------------------------------------------------------------
// Approved derived semantics
// ---------------------------------------------------------------------------

void test('the Tele / CS / CA top edge is open to the main circulation', () => {
  const seamY = worldY(244);
  const separatorX = worldX(1156);
  for (const wall of officeMap.walls) {
    const horizontal = wall.rect.w > wall.rect.h;
    if (horizontal && wall.rect.y <= seamY && wall.rect.y + wall.rect.h >= seamY && wall.rect.x + wall.rect.w > separatorX + 1e-6) {
      assert.fail(`wall ${wall.id} crosses the open Tele top`);
    }
  }
  for (const x of [worldX(1180), worldX(1300), worldX(1440)]) {
    assert.equal(isWalkable(officeMap, x, worldY(270)), true, `Tele top open at source x=${x}`);
  }
});

void test('the Wastafel north path is open all the way to the main circulation', () => {
  const x = worldX(537);
  for (let y = worldY(232); y <= worldY(472); y += 20) {
    assert.equal(isWalkable(officeMap, x, y), true, `wash path open at world y=${y}`);
  }
});

void test('Gudang, both toilets and the Server are sealed, but their door approaches are walkable', () => {
  const sealed: Array<[string, Point]> = [
    ['gudang', { x: 551.25, y: 545 }],
    ['toilet-wanita', { x: 617.5, y: 566 }],
    ['toilet-pria', { x: 720.5, y: 560 }],
    ['server', { x: 808.75, y: 540 }],
  ];
  for (const [id, point] of sealed) {
    assert.equal(isWalkable(officeMap, point.x, point.y), false, `${id} interior is sealed`);
    assert.ok(officeMap.blocks.some((block) => block.kind === 'sealed' && rectContainsPoint(block.rect, point.x, point.y)), `${id} has a sealed block`);
  }
  assert.equal(isWalkable(officeMap, 551.25, worldY(384)), true, 'Gudang door approach (corridor side)');
  assert.equal(isWalkable(officeMap, 655, worldY(440)), true, 'Toilet Wanita door approach (strip side)');
  assert.equal(isWalkable(officeMap, 687, worldY(430)), true, 'Toilet Pria door approach (strip side)');
  assert.equal(isWalkable(officeMap, 890, 550), true, 'Server door approach (Desk Collection side)');
});

void test('the Best Agent Performance board is a slim, wall-mounted, non-solid board with a hotspot', () => {
  const board = officeMap.furniture.find((item) => item.id === 'F-WA-BOARD-BAP');
  assert.ok(board, 'the board exists');
  assert.equal(board?.kind, 'board');
  assert.equal(board?.solid, false, 'the board is wall-mounted, so non-solid');
  assert.equal(board?.zone, 'desk-collection');
  assert.ok(board!.rect.w <= 10, 'the board is slim (<= 10 world px deep)');

  const wall = officeMap.walls.find((entry) => entry.id === 'w-m2-east')!;
  assert.ok(board!.rect.x >= wall.rect.x + wall.rect.w - 1, 'the board sits on the Meeting-2 east face');

  const hotspot = officeMap.hotspots.find((entry) => entry.kind === 'board');
  assert.equal(hotspot?.id, 'hs-board');
  assert.equal(hotspot?.zone, 'desk-collection');
});

void test('there is no invented Meeting 2 screen (furniture or hotspot)', () => {
  assert.equal(officeMap.furniture.filter((item) => item.kind === 'screen').length, 0, 'no screen furniture at all');
  assert.equal(officeMap.hotspots.filter((entry) => entry.id === 'hs-screen-meeting-2').length, 0);
  assert.equal(officeMap.hotspots.filter((entry) => entry.kind === 'screen').length, 0);
});

void test('the certificate table has its own hotspot distinct from the board', () => {
  const certFurniture = officeMap.furniture.find((item) => item.id === 'F-PS-CERT-TABLE');
  assert.ok(certFurniture, 'the certificate table furniture exists');
  const cert = officeMap.hotspots.find((entry) => entry.kind === 'certificate-table');
  assert.equal(cert?.id, 'hs-cert-table');
  assert.equal(cert?.zone, certFurniture!.zone);
  assert.deepEqual(cert?.rect, certFurniture!.rect);
});

void test('the west lane stays solid-free and corrected side chairs remain non-solid outside the banks', () => {
  const wall = officeMap.walls.find((entry) => entry.id === 'w-m2-east')!;
  const wallFace = wall.rect.x + wall.rect.w;
  const bankLeft = Math.min(officeMap.furniture.find((item) => item.id === 'F-DC-BANK-TOP')!.rect.x, officeMap.furniture.find((item) => item.id === 'F-DC-BANK-BOTTOM')!.rect.x);
  const laneWidth = bankLeft - wallFace;
  assert.ok(laneWidth >= officeMap.actor.halfWidth * 2, `west lane ${laneWidth} must fit the ${officeMap.actor.halfWidth * 2}-wide actor`);

  const lane: Rect = { x: wallFace, y: worldY(244), w: laneWidth, h: worldY(501) - worldY(244) };
  for (const item of officeMap.furniture) {
    if (!item.solid) continue;
    assert.equal(intersectRect(lane, item.rect), null, `solid ${item.id} intrudes into the west lane`);
  }
  for (const id of ['F-DC-T-SIDE', 'F-DC-B-SIDE']) {
    const chair = officeMap.furniture.find((item) => item.id === id)!;
    assert.equal(chair.solid, false);
    assert.ok(chair.rect.x < bankLeft, `${id} sits left of the bank`);
    for (const deskId of ['F-DC-BANK-TOP', 'F-DC-BANK-BOTTOM']) {
      const desk = officeMap.furniture.find((item) => item.id === deskId)!;
      assert.equal(intersectRect(chair.rect, desk.rect), null, `${id} clears ${deskId}`);
    }
  }
});

// ---------------------------------------------------------------------------
// Collision (actor footprint, not a bare point)
// ---------------------------------------------------------------------------

void test('actorFootBox models width and feet, anchored at the feet', () => {
  assert.deepEqual(actorFootBox(100, 200, { halfWidth: 9, feet: 12 }), { x: 91, y: 188, w: 18, h: 12 });
});

void test('walls, columns and solid furniture block movement', () => {
  const wall = officeMap.walls.find((entry) => entry.id === 'w-toprow-bottom')!;
  assert.equal(isBlocked(officeMap, wall.rect.x + 40, wall.rect.y + wall.rect.h / 2), true, 'full wall blocks');

  const column = officeMap.columns[0]!;
  assert.equal(isBlocked(officeMap, column.rect.x + column.rect.w / 2, column.rect.y + column.rect.h / 2), true, 'column blocks');

  const desk = officeMap.furniture.find((entry) => entry.solid && entry.kind === 'desk')!;
  assert.equal(isBlocked(officeMap, desk.rect.x + desk.rect.w / 2, desk.rect.y + desk.rect.h / 2), true, 'solid desk blocks');
});

void test('chair furniture is decorative and does not block', () => {
  const chair = officeMap.furniture.find((entry) => entry.kind === 'chair')!;
  assert.equal(chair.solid, false);
  assert.equal(isWalkable(officeMap, chair.rect.x + chair.rect.w / 2, chair.rect.y + chair.rect.h / 2), true);
});

void test('every door and gap opening is passable by the real actor', () => {
  for (const opening of officeMap.openings) {
    const horizontal = opening.orientation === 'horizontal';
    const cx = opening.rect.x + opening.rect.w / 2;
    const cy = opening.rect.y + opening.rect.h / 2;
    const candidates = horizontal
      ? [{ x: cx, y: cy }, { x: cx, y: cy - 8 }, { x: cx, y: cy + 8 }]
      : [{ x: cx, y: cy }, { x: cx - 8, y: cy }, { x: cx + 8, y: cy }];
    assert.ok(candidates.some((point) => isWalkable(officeMap, point.x, point.y)), `opening ${opening.id} is passable`);
  }
});

void test('the actor footprint blocks a body whose centre point would be clear', () => {
  const wall = officeMap.walls.find((entry) => entry.id === 'w-toprow-bottom')!;
  const x = 700;
  const y = wall.rect.y + wall.rect.h + 4;
  assert.equal(officeMap.walls.some((entry) => rectContainsPoint(entry.rect, x, y)), false, 'centre point is not inside a wall');
  assert.equal(isBlocked(officeMap, x, y), true, 'foot box still hits the wall');
  assert.equal(isBlocked(officeMap, x, y, { halfWidth: 0.1, feet: 0.1 }), false, 'a pin-point body fits');
});

void test('walkable spots across the map are reported as free', () => {
  const samples: Point[] = [
    { x: 300, y: 780 }, // lobby
    { x: 1542.5, y: 88.75 }, // Bilik Geng Kami, near seat 1
    { x: 1000, y: 260 }, // main circulation
    { x: 1100, y: 480 }, // Desk Collection, between the banks
    { x: 1650, y: 480 }, // Tele / CS / CA
  ];
  for (const point of samples) assert.equal(isWalkable(officeMap, point.x, point.y), true, `free at ${point.x},${point.y}`);
});

// ---------------------------------------------------------------------------
// Geometry primitives
// ---------------------------------------------------------------------------

void test('rectangle primitives behave as documented', () => {
  assert.equal(rectArea({ x: 0, y: 0, w: 10, h: 4 }), 40);
  assert.equal(rectContainsPoint({ x: 0, y: 0, w: 10, h: 10 }, 5, 5), true);
  assert.equal(rectContainsPoint({ x: 0, y: 0, w: 10, h: 10 }, 11, 5), false);
  assert.equal(rectContainsRect({ x: 0, y: 0, w: 10, h: 10 }, { x: 2, y: 2, w: 4, h: 4 }), true);
  assert.equal(rectContainsRect({ x: 0, y: 0, w: 10, h: 10 }, { x: 2, y: 2, w: 20, h: 4 }), false);
  assert.deepEqual(intersectRect({ x: 0, y: 0, w: 10, h: 10 }, { x: 5, y: 5, w: 10, h: 10 }), { x: 5, y: 5, w: 5, h: 5 });
  assert.equal(intersectRect({ x: 0, y: 0, w: 10, h: 10 }, { x: 10, y: 0, w: 10, h: 10 }), null, 'edge-touching rects do not overlap');
});

// ---------------------------------------------------------------------------
// Zone lookup + seats
// ---------------------------------------------------------------------------

void test('zoneAt resolves the containing zone, preferring the smallest match', () => {
  assert.equal(zoneAt(officeMap, 300, 780)?.id, 'lobby-besar');
  assert.equal(zoneAt(officeMap, 1542.5, 88.75)?.id, BILIK_GENG_ZONE_ID);
  assert.equal(zoneAt(officeMap, 1000, 260)?.id, 'lorong-utama');
  assert.equal(zoneAt(officeMap, 550, 430)?.id, 'pantry');
  assert.equal(zoneAt(officeMap, 1100, 480)?.id, 'desk-collection');
  assert.equal(zoneAt(officeMap, 0, 0), undefined);

  const layered = clone();
  layered.zones.push({ id: 'everywhere', name: 'Everywhere', kind: 'open', rect: { x: 0, y: 0, w: officeMap.width, h: officeMap.height } });
  assert.equal(zoneAt(layered, 300, 780)?.id, 'lobby-besar', 'the smaller zone wins');
});

void test('seatFor maps a character id to its assigned seat', () => {
  assert.equal(seatFor(officeMap, 1)?.id, 'seat-1');
  assert.equal(seatFor(officeMap, 6)?.id, 'seat-6');
  assert.equal(seatFor(officeMap, 99), undefined);
});

// ---------------------------------------------------------------------------
// Hotspots
// ---------------------------------------------------------------------------

void test('nearestHotspot finds hotspots by proximity and supports kind filters', () => {
  const seat = seatFor(officeMap, 1)!;
  const nearSeat = nearestHotspot(officeMap, seat.x, seat.y);
  assert.equal(nearSeat?.hotspot.id, 'hs-seat-1');
  assert.equal(nearSeat?.distance, 0);

  assert.equal(nearestHotspot(officeMap, 0, 0, { maxDistance: 40 }), null);

  const lift = officeMap.hotspots.find((hotspot) => hotspot.kind === 'lift')!;
  const found = nearestHotspot(officeMap, lift.rect.x + lift.rect.w / 2, lift.rect.y + lift.rect.h / 2, { kinds: ['lift'] });
  assert.equal(found?.hotspot.id, lift.id);

  const kinds: HotspotKind[] = ['exit'];
  const exit = officeMap.hotspots.find((hotspot) => hotspot.kind === 'exit')!;
  const exitFound = nearestHotspot(officeMap, exit.rect.x + exit.rect.w / 2, exit.rect.y + exit.rect.h / 2, { kinds });
  assert.equal(exitFound?.hotspot.action, 'status-pulang');
  assert.ok(DEFAULT_HOTSPOT_RANGE >= 40);
});

void test('the manifest carries the required data-driven hotspots', () => {
  const byKind = (kind: HotspotKind) => officeMap.hotspots.filter((hotspot) => hotspot.kind === kind);
  assert.equal(byKind('lift').length, 4, 'four lifts');
  assert.equal(byKind('seat').length, 6, 'six assigned chairs');
  assert.equal(byKind('gudang').length, 1, 'locked Gudang');
  assert.equal(byKind('fridge').length, 1, 'pantry fridge');
  assert.equal(byKind('dispenser').length, 4, 'pantry + HR/IT/Finance dispensers');
  assert.equal(byKind('board').length, 1, 'Best Agent board');
  assert.equal(byKind('certificate-table').length, 1, 'certificate table');
  assert.equal(byKind('server').length, 1, 'restricted server notice');
  assert.equal(byKind('reception').length, 1, 'reception info');
  assert.equal(byKind('exit').length, 1, 'single exit hotspot');
  assert.equal(byKind('screen').length, 0, 'no screens');

  for (const hotspot of officeMap.hotspots) {
    assert.ok(officeMap.zones.some((zone) => zone.id === hotspot.zone), `${hotspot.id} references a real zone`);
  }
});

// ---------------------------------------------------------------------------
// Camera clamping
// ---------------------------------------------------------------------------

void test('clampCamera keeps the view inside the world for desktop and mobile', () => {
  const desktop = { w: 960, h: 540 };
  assert.deepEqual(clampCamera(officeMap, desktop, { x: 960, y: 480 }), { x: 480, y: 210 });
  assert.deepEqual(clampCamera(officeMap, desktop, { x: 0, y: 0 }), { x: 0, y: 0 });
  assert.deepEqual(clampCamera(officeMap, desktop, { x: 5000, y: 5000 }), { x: 960, y: 420 });

  const mobile = { w: 560, h: 360 };
  assert.deepEqual(clampCamera(officeMap, mobile, { x: 100, y: 100 }), { x: 0, y: 0 });
  assert.deepEqual(clampCamera(officeMap, mobile, { x: 1600, y: 800 }), { x: 1320, y: 600 });

  const oversized = { w: 2400, h: 1200 };
  assert.deepEqual(clampCamera(officeMap, oversized, { x: 960, y: 480 }), { x: 0, y: 0 }, 'a view larger than the world pins to the origin');
});

// ---------------------------------------------------------------------------
// Route reachability (grid BFS over the walkable space, real 18x12 actor)
// ---------------------------------------------------------------------------

const STEP = 6;

function reachableFrom(manifest: OfficeManifest, from: Point): Set<number> {
  const cols = Math.floor(manifest.width / STEP) + 1;
  const rows = Math.floor(manifest.height / STEP) + 1;
  const index = (i: number, j: number): number => j * cols + i;

  const start = index(Math.round(from.x / STEP), Math.round(from.y / STEP));
  assert.equal(isWalkable(manifest, from.x, from.y), true, `BFS origin ${from.x},${from.y} is walkable`);

  const seen = new Set<number>([start]);
  const queue: number[] = [start];
  for (let head = 0; head < queue.length; head += 1) {
    const i = queue[head]! % cols;
    const j = (queue[head]! - i) / cols;
    for (const [di, dj] of [
      [1, 0],
      [-1, 0],
      [0, 1],
      [0, -1],
    ] as const) {
      const ni = i + di;
      const nj = j + dj;
      if (ni < 0 || nj < 0 || ni >= cols || nj >= rows) continue;
      const key = index(ni, nj);
      if (seen.has(key)) continue;
      if (isBlocked(manifest, ni * STEP, nj * STEP)) continue;
      seen.add(key);
      queue.push(key);
    }
  }
  return seen;
}

function reaches(manifest: OfficeManifest, seen: Set<number>, point: Point): boolean {
  const cols = Math.floor(manifest.width / STEP) + 1;
  const rows = Math.floor(manifest.height / STEP) + 1;
  const ci = Math.round(point.x / STEP);
  const cj = Math.round(point.y / STEP);
  for (let di = -1; di <= 1; di += 1) {
    for (let dj = -1; dj <= 1; dj += 1) {
      const i = ci + di;
      const j = cj + dj;
      if (i < 0 || j < 0 || i >= cols || j >= rows) continue;
      if (seen.has(j * cols + i)) return true;
    }
  }
  return false;
}

void test('every required area is reachable from the lobby entrance with the real actor', () => {
  const seen = reachableFrom(officeMap, { x: 300, y: 780 });
  const goals: Array<[string, Point]> = [
    ['Reception', { x: 480, y: 300 }],
    ['Main circulation', { x: 1000, y: 260 }],
    ['Ruang Meeting 1', { x: 560, y: 120 }],
    ['Ruangan HRGA', { x: 775, y: 215 }],
    ['Bilik Komisaris', { x: 985, y: 210 }],
    ['Bilik Product Manager', { x: 1040, y: 210 }],
    ['Bilik IT', { x: 1180, y: 90 }],
    ['Bilik Direktur Finance', { x: 1330, y: 210 }],
    ['Pantry', { x: 560, y: 450 }],
    ['Wash path', { x: worldX(537), y: worldY(440) }],
    ['Wastafel', { x: 671, y: 600 }],
    ['Ruang Meeting 2', { x: 800, y: 320 }],
    ['Desk Collection (lower bank)', { x: 1100, y: 480 }],
    ['Tele / CS / CA', { x: 1650, y: 480 }],
    ['Server door approach', { x: 890, y: 550 }],
  ];
  for (const [name, point] of goals) {
    assert.equal(isWalkable(officeMap, point.x, point.y), true, `${name} goal is walkable`);
    assert.equal(reaches(officeMap, seen, point), true, `${name} is reachable from the lobby`);
  }
});

void test('the six assigned seats are reachable from the lobby entrance', () => {
  const seen = reachableFrom(officeMap, { x: 300, y: 780 });
  for (const seat of officeMap.seats) {
    assert.equal(reaches(officeMap, seen, { x: seat.x, y: seat.y }), true, `${seat.id} is reachable`);
  }
});

void test('every non-sealed zone has a reachable standable cell', () => {
  const seen = reachableFrom(officeMap, { x: 300, y: 780 });
  const cols = Math.floor(officeMap.width / STEP) + 1;
  const sealed = new Set(['gudang', 'toilet-wanita', 'toilet-pria', 'server']);
  for (const zone of officeMap.zones) {
    if (sealed.has(zone.id)) continue;
    let found = false;
    for (let x = zone.rect.x + STEP; x < zone.rect.x + zone.rect.w && !found; x += STEP) {
      for (let y = zone.rect.y + STEP; y < zone.rect.y + zone.rect.h && !found; y += STEP) {
        if (zoneAt(officeMap, x, y)?.id !== zone.id) continue;
        if (seen.has(Math.round(y / STEP) * cols + Math.round(x / STEP))) found = true;
      }
    }
    assert.equal(found, true, `${zone.id} has a reachable cell`);
  }
});
