'use client';

import { FormEvent, useEffect, useRef, useState } from 'react';
import { Coffee, Gamepad2, MessageCircle, Send, Settings2 } from 'lucide-react';

type Direction='up'|'down'|'left'|'right'; type Player={id:number;name:string,sprite:number,x:number,y:number,direction:Direction,walking:boolean,status:string,online:boolean,sitting?:boolean};
type Chat={id:number;name:string;text:string;time:string;sprite:number};
const WORLD={w:960,h:540}; const SPEED=125;
const COLLIDERS=[{x:0,y:0,w:960,h:18},{x:0,y:510,w:960,h:30},{x:0,y:0,w:18,h:540},{x:942,y:0,w:18,h:540},{x:174,y:150,w:305,h:190},{x:480,y:178,w:125,h:120},{x:746,y:182,w:105,h:125}];
const CHAIRS=[{x:250,y:345},{x:865,y:235},{x:250,y:125},{x:630,y:235},{x:395,y:345},{x:395,y:125}];
const START:Player[]=[
 {id:1,name:'Farkhan',sprite:0,x:245,y:385,direction:'up',walking:false,status:'Available',online:true}, {id:2,name:'Surya',sprite:1,x:880,y:250,direction:'left',walking:false,status:'Sibuk',online:true},
 {id:3,name:'Imam',sprite:2,x:245,y:105,direction:'down',walking:false,status:'Available',online:true}, {id:4,name:'Malla',sprite:3,x:635,y:250,direction:'left',walking:false,status:'Meeting',online:true},
 {id:5,name:'Siska',sprite:4,x:395,y:385,direction:'up',walking:false,status:'Istirahat',online:true}, {id:6,name:'Mona',sprite:5,x:395,y:105,direction:'down',walking:false,status:'Available',online:true},
];
const INITIAL_CHAT:Chat[]=[{id:1,name:'Malla',text:'Makan siang nanti di mana?',time:'11:42',sprite:3},{id:2,name:'Surya',text:'Yang dekat aja, energi tipis.',time:'11:43',sprite:1},{id:3,name:'Farkhan',text:'Siap, nanti kita voting 😌',time:'11:44',sprite:0}];

export default function Home(){
 const canvasRef=useRef<HTMLCanvasElement>(null),playersRef=useRef<Player[]>(structuredClone(START)),keys=useRef(new Set<string>()),assets=useRef<{map?:HTMLImageElement,sprites?:HTMLImageElement}>({});
 const [players,setPlayers]=useState(START); const [selected,setSelected]=useState<Player|null>(null); const [chat,setChat]=useState(INITIAL_CHAT); const [draft,setDraft]=useState(''); const [chatOpen,setChatOpen]=useState(false); const [hint,setHint]=useState('WASD / panah untuk bergerak');
 useEffect(()=>{const map=new Image(),sprites=new Image();map.src='room/bilik-geng-v3-960.jpg';sprites.src='avatar/team-six.png';assets.current={map,sprites};let raf=0,last=performance.now(),frame=0;
  const down=(e:KeyboardEvent)=>{if(e.target instanceof HTMLTextAreaElement)return;if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright'].includes(e.key.toLowerCase())){e.preventDefault();keys.current.add(e.key.toLowerCase())}if(['e','x'].includes(e.key.toLowerCase()))interact();if(e.key==='Enter')setChatOpen(true);if(e.key==='Escape'){setChatOpen(false);setSelected(null)}if(['1','2','3','4'].includes(e.key))emote(Number(e.key)-1)};
  const up=(e:KeyboardEvent)=>keys.current.delete(e.key.toLowerCase());addEventListener('keydown',down);addEventListener('keyup',up);
  function loop(now:number){const dt=Math.min((now-last)/1000,.04);last=now;update(dt);draw(frame++);raf=requestAnimationFrame(loop)}raf=requestAnimationFrame(loop);
  return()=>{cancelAnimationFrame(raf);removeEventListener('keydown',down);removeEventListener('keyup',up)}
 },[]);
 function blocked(x:number,y:number){const r={x:x-12,y:y-14,w:24,h:28};return COLLIDERS.some(c=>r.x<c.x+c.w&&r.x+r.w>c.x&&r.y<c.y+c.h&&r.y+r.h>c.y)}
 function update(dt:number){const p=playersRef.current[0];let dx=0,dy=0;if(keys.current.has('a')||keys.current.has('arrowleft')){dx=-1;p.direction='left'}if(keys.current.has('d')||keys.current.has('arrowright')){dx=1;p.direction='right'}if(keys.current.has('w')||keys.current.has('arrowup')){dy=-1;p.direction='up'}if(keys.current.has('s')||keys.current.has('arrowdown')){dy=1;p.direction='down'}const len=Math.hypot(dx,dy)||1;dx=dx/len*SPEED*dt;dy=dy/len*SPEED*dt;p.walking=!!(dx||dy);p.sitting=false;if(!blocked(p.x+dx,p.y))p.x+=dx;if(!blocked(p.x,p.y+dy))p.y+=dy;if(p.walking)setPlayers([...playersRef.current])}
 function draw(tick:number){const canvas=canvasRef.current,ctx=canvas?.getContext('2d'),map=assets.current.map,sheet=assets.current.sprites;if(!canvas||!ctx||!map?.complete)return;const mobile=innerWidth<860,vw=mobile?560:960,vh=mobile?360:540;if(canvas.width!==vw||canvas.height!==vh){canvas.width=vw;canvas.height=vh}const me=playersRef.current[0],camX=mobile?Math.max(0,Math.min(WORLD.w-vw,me.x-vw/2)):0,camY=mobile?Math.max(0,Math.min(WORLD.h-vh,me.y-vh/2)):0;ctx.imageSmoothingEnabled=false;ctx.clearRect(0,0,vw,vh);ctx.drawImage(map,camX,camY,vw,vh,0,0,vw,vh);playersRef.current.filter(p=>p.online).sort((a,b)=>a.y-b.y).forEach(p=>drawPlayer(ctx,p,camX,camY,sheet,tick));}
 function drawPlayer(ctx:CanvasRenderingContext2D,p:Player,camX:number,camY:number,sheet:HTMLImageElement|undefined,tick:number){if(!sheet?.complete)return;const cellW=sheet.naturalWidth/6,cellH=sheet.naturalHeight/2,walkFrame=p.walking?Math.floor(tick/8)%2:0;const dw=p.sprite===0?36:p.sprite===1?40:34,dh=p.sitting?42:58,x=p.x-camX-dw/2,y=p.y-camY-dh;if(p.direction==='left'){ctx.save();ctx.translate(x+dw,y);ctx.scale(-1,1);ctx.drawImage(sheet,p.sprite*cellW,walkFrame*cellH,cellW,cellH,0,0,dw,dh);ctx.restore()}else{ctx.save();if(p.direction==='up')ctx.filter='brightness(.72) saturate(.8)';ctx.drawImage(sheet,p.sprite*cellW,walkFrame*cellH,cellW,cellH,x,y,dw,dh);ctx.restore()}ctx.font='bold 11px Trebuchet MS';const tw=ctx.measureText(p.name).width;ctx.fillStyle='#29263b';ctx.fillRect(p.x-camX-tw/2-5,p.y-camY+2,tw+10,17);ctx.fillStyle='#fff8e8';ctx.fillText(p.name,p.x-camX-tw/2,p.y-camY+14);if(p.id===1){ctx.strokeStyle='#ffe078';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(p.x-camX,p.y-camY,22,8,0,0,Math.PI*2);ctx.stroke()}}
 function interact(){const p=playersRef.current[0],chair=CHAIRS.find(c=>Math.hypot(c.x-p.x,c.y-p.y)<42);if(chair){p.x=chair.x;p.y=chair.y;p.sitting=true;p.walking=false;setHint('Duduk di kursi • gerak untuk berdiri');setPlayers([...playersRef.current]);return}if(p.y>470&&p.x>180&&p.x<320){p.status='Pulang';setHint('Status berubah menjadi Pulang');setPlayers([...playersRef.current]);return}if(p.x<90){alert('📌 Pengumuman: Jangan lupa isi galon kalau habis.');return}setHint('Tidak ada objek untuk berinteraksi di dekatmu')}
 function emote(i:number){const icons=['👋','😂','👏','☕'];setHint(`${icons[i]} Emote dikirim`);setTimeout(()=>setHint('WASD / panah untuk bergerak'),1800)}
 function hold(k:string,on:boolean){on?keys.current.add(k):keys.current.delete(k)}
 function send(e:FormEvent){e.preventDefault();const text=draft.trim().slice(0,500);if(!text)return;setChat(v=>[...v,{id:Date.now(),name:'Farkhan',text,time:new Date().toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit'}),sprite:0}]);setDraft('')}
 return <main className="canvas-app"><header className="canvas-header"><div className="pixel-logo">NK</div><div><strong>Nongkrong Kantor</strong><small>Bilik Geng Kami • Blugreen Lantai 6</small></div><span className="online-count"><i/>6 online</span><button onClick={()=>setSelected(players[0])}><Settings2/>Farkhan</button></header><div className="canvas-layout"><section className="game-column"><div className="game-frame"><canvas ref={canvasRef} onClick={e=>{const r=e.currentTarget.getBoundingClientRect(),scaleX=e.currentTarget.width/r.width,scaleY=e.currentTarget.height/r.height,x=(e.clientX-r.left)*scaleX,y=(e.clientY-r.top)*scaleY;const hit=playersRef.current.find(p=>Math.hypot(p.x-x,p.y-y)<34);if(hit)setSelected({...hit})}}/><div className="game-hint"><Gamepad2/>{hint}</div></div><div className="game-toolbar"><button onClick={()=>setSelected(players[0])}>Avatar</button><button onClick={()=>setSelected(players[0])}>Status: {players[0].status}</button><button onClick={()=>setChatOpen(true)}><MessageCircle/>Chat</button></div><MobileControls hold={hold} interact={interact} chat={()=>setChatOpen(true)}/></section><ChatPanel chat={chat} draft={draft} setDraft={setDraft} send={send}/></div>
 {selected&&<div className="canvas-modal" onClick={()=>setSelected(null)}><section onClick={e=>e.stopPropagation()}><button onClick={()=>setSelected(null)}>×</button><span className="profile-avatar">{selected.name[0]}</span><h2>{selected.name}</h2><p>● {selected.online?'Online':'Offline'} • {selected.status}</p>{selected.id===1&&<div className="status-options">{['Available','Sibuk','Meeting','Istirahat','Pulang'].map(s=><button key={s} onClick={()=>{playersRef.current[0].status=s;setPlayers([...playersRef.current]);setSelected({...playersRef.current[0]})}}>{s}</button>)}</div>}</section></div>}
 {chatOpen&&<div className="mobile-chat-drawer"><button onClick={()=>setChatOpen(false)}>×</button><ChatPanel chat={chat} draft={draft} setDraft={setDraft} send={send}/></div>}</main>
}

function ChatPanel({chat,draft,setDraft,send}:{chat:Chat[];draft:string;setDraft:(s:string)=>void;send:(e:FormEvent)=>void}){return <aside className="canvas-chat"><header><small>OBROLAN</small><strong>Ruang rame-rame</strong></header><div>{chat.map(m=><article key={m.id}><b>{m.name}<time>{m.time}</time></b><p>{m.text}</p></article>)}</div><form onSubmit={send}><textarea value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Tulis pesan..."/><button><Send/></button></form></aside>}
function MobileControls({hold,interact,chat}:{hold:(k:string,on:boolean)=>void;interact:()=>void;chat:()=>void}){const btn=(k:string,label:string)=><button onPointerDown={()=>hold(k,true)} onPointerUp={()=>hold(k,false)} onPointerLeave={()=>hold(k,false)}>{label}</button>;return <div className="mobile-controls"><div className="virtual-dpad"><i/>{btn('w','▲')}<i/>{btn('a','◀')}{btn('s','▼')}{btn('d','▶')}</div><button className="interact-button" onClick={interact}>E<br/><small>Interaksi</small></button><button className="mobile-chat-button" onClick={chat}><MessageCircle/>Chat</button></div>}
